ignore:
  - 'indexers/**/*'
  - 'lib/gzip_xml_reader.rb'
  - 'lib/hathitrust/**/*'
  - 'lib/ht_traject/**/*'
  - 'lib/ht_traject.rb'
  - 'lib/traject/**/*'
  - 'lib/translation_maps/**/*'
  - 'lib/umich_traject/**/*'
  - 'lib/umich_traject.rb'
  - 'readers/**/*'
  - 'solr/**/*'
  - 'writers/**/*'
