#!/bin/bash

JRUBY="/htsolr/catalog/bin/jruby-1.7.6/bin/jruby"
TDIR="/htsolr/catalog/bin/ht_traject"
DDIR=/htsolr/catalog/prep

# Find yesterday's date
datestr=`date --date "now -1 day" "+%Y%m%d"`

marcfile="${DDIR}/zephir_upd_${datestr}.json.gz"
delfile="${DDIR}/zephir_upd_${datestr}_delete.txt"


if [ -f $delfile ] 
then
  echo Deleting from $delfile
  $JRUBY $TDIR/delete_ids $delfile
else
  echo "No Deletes: Could not find file '$delfile'"
fi


if [ -f $marcfile ] 
then
  echo Indexing from $marcfile
  $TDIR/tindex.sh $marcfile
else
  echo "No indexing: Could not find file '$marcfile'"
fi



