---
version: '3'

services:
  traject:
    build: .
    volumes:
      - .:/app
      - gem_cache:/gems
    environment:
      - SOLR_URL=http://solr-sdr-catalog:9033/solr/catalog
      - redirect_file=/dev/null
      - NO_DB=1
      - DDIR=/app/examples

  solr-sdr-catalog:
    build: solr
    ports:
      - "9033:9033"

  test:
    build: .
    volumes:
      - .:/app
      - gem_cache:/gems
    command: bash -c "wait-for solr-sdr-catalog:9033 && JRUBY_OPTS="--debug" bundle exec rspec"
    environment:
      - SOLR_URL=http://solr-sdr-catalog:9033/solr/catalog
      - redirect_file=/dev/null
      - NO_DB=1
      - DDIR=/app/examples
    depends_on:
      - solr-sdr-catalog

volumes:
  gem_cache:
