---

x-condition-healthy: &healthy
  condition: service_healthy

x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 10s
  start_period: 10s
  retries: 5

services:
  traject:
    build: 
      context: .
      target: development
    volumes:
      - .:/app
      - gem_cache:/gems
    environment:
      - SOLR_URL=http://solr-sdr-catalog:9033/solr/catalog
      - redirect_file=/dev/null
      - NO_DB=1
    network_mode: host
    command: sleep infinity

  test:
    build: 
      context: .
      target: development
    volumes:
      - .:/app
      - gem_cache:/gems
    command: bundle exec rspec
    environment:
      - JRUBY_OPTS=--debug
      - PUSHGATEWAY=http://pushgateway:9091
      - REDIRECT_FILE=/dev/null
      - SOLR_URL=http://solr-sdr-catalog:9033/solr/catalog
    depends_on:
      pushgateway: *healthy
      mariadb: *healthy
      solr-sdr-catalog: *healthy

  solr-sdr-catalog:
    build: solr
    ports:
      - "9033:9033"
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "curl","-s","-f","http://localhost:9033/solr/catalog/admin/ping" ]

  mariadb:
    image: ghcr.io/hathitrust/db-image:latest
    ports:
      - "3306:3306"
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9092:9091
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "wget", "--quiet", "--tries=1", "-O", "/dev/null", "pushgateway:9091/-/healthy" ]

volumes:
  gem_cache:
