source "https://rubygems.org"

group :development, :test do
  gem "bundler", "~>2.0"
  gem "climate_control"
  gem "rake", "~> 13.0"
  gem "pry"
  gem "rspec"
  gem "simplecov"
  gem "simplecov-lcov"
  gem "standard"
  gem "timecop"
end

gem "canister", "~> 0.9.2"
gem "date_named_file"
gem "dotenv"
gem "faraday"
gem "http", "~>5.0"
gem "httpclient"
gem "httpx"
gem "library_stdnums"
gem "marc-fastxmlwriter", "~> 1.1"
gem "match_map"
gem "push_metrics", git: "https://github.com/hathitrust/push_metrics"
gem "rsolr"
gem "semantic_logger"
gem "sequel"
gem "thor"
gem "traject", "~>3.0"
gem "traject_alephsequential_reader"
gem "traject_umich_format"
gem "yell"
gem "zinzout"

if defined? JRUBY_VERSION
  gem "jdbc-mysql"
  gem "naconormalizer"
  gem "traject-marc4j_reader"
end
