name: Deploy

on:
    workflow_dispatch:
        inputs:
            branch_hash:
                description: Branch sha or revision to deploy (Defaults to branch sha)
            environments:
                description: The environment to deploy to
                type: choice
                default: testing
                options:
                    - testing
                    - production

jobs:
    deploy:
        permissions:
            contents: read
            packages: write
        name: Deploy to ${{inputs.environments}}
        uses: hathitrust/github_actions/.github/workflows/deploy.yml@70aa6270dd1555f0e52bff3d7894ecdb7c76f80f # v2.1.1
        with:
            image: ghcr.io/${{ github.repository }}:${{ inputs.branch_hash || github.sha}}
            file: environments/metadata_processing/${{inputs.environments}}/catalog-indexing-image.txt
            CONFIG_REPO_FULL_NAME: ${{ vars.CONFIG_REPO_FULL_NAME }}
        secrets: inherit
