name: Run Tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Log in to package registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up tests
        run: |
          docker compose build
          docker compose run --rm test bundle install

      - name: Run standardrb
        run: docker compose run --rm test bundle exec standardrb

      - name: Run tests
        run: docker compose run --rm test

      - name: Run solrcloud tests
        run: docker compose run --rm test-solrcloud

      - name: Report to Coveralls
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.7
        with:
          github-token: ${{ secrets.github_token }}
