name: Run Tests

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Log in to package registry
        uses: docker/login-action@v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up tests
        run: |
          docker compose build
          docker compose run test bundle install

      - name: Run standardrb
        run: docker compose run test bundle exec standardrb

      - name: Run tests
        run: docker compose run test

      - name: Report to Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.github_token }}
